spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diary_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

# 파일 업로드 경로
file:
  upload-dir: ./uploads/images

# CORS 설정
cors:
  allowed-origins: http://localhost:3000
